# Generated by Django 4.0 on 2021-12-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trend',
            field=models.IntegerField(default=0),
        ),
    ]
