# Generated by Django 4.0 on 2021-12-19 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_product_trend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['trend']},
        ),
    ]
