# Generated by Django 4.0 on 2021-12-19 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_alter_category_options_notify_clientorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notify',
            options={'verbose_name_plural': 'Notifications'},
        ),
    ]
