# Generated by Django 4.0 on 2021-12-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='production_state',
            field=models.CharField(default='Maharashtra', max_length=25),
            preserve_default=False,
        ),
    ]
