# Generated by Django 4.0 on 2021-12-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='order',
        ),
    ]
