# Generated by Django 4.0 on 2021-12-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_manufacturerorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturerorder',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manufacturerorder',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturerorder',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
