# Generated by Django 4.0 on 2021-12-20 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_rename_total_price_manufacturerorder_total_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='m_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogue.manufacturerorder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientorder',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='manufacturerorder',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
