# Generated by Django 4.0 on 2021-12-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_clientorder_m_order_clientorder_refunded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='shipping_charge',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='total_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='manufacturerorder',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='manufacturerorder',
            name='final_payment',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='manufacturerorder',
            name='total_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='notify',
            name='below',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='final_payment',
            field=models.FloatField(),
        ),
    ]
