# Generated by Django 3.2.10 on 2021-12-20 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_alter_clientorder_shipping_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='m_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogue.manufacturerorder'),
        ),
    ]
