# Generated by Django 3.2.10 on 2021-12-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_alter_clientorder_m_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
