# Generated by Django 3.2.10 on 2021-12-21 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_alter_product_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_on',
        ),
    ]
