# Generated by Django 4.0 on 2021-12-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_myuser_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='refund_balance',
            field=models.IntegerField(default=0),
        ),
    ]
