# Generated by Django 4.0 on 2021-12-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_myuser_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='city',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='state',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
