# Generated by Django 4.0 on 2021-12-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_myuser_city_alter_myuser_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='refund_balance',
            field=models.FloatField(default=0),
        ),
    ]
